

INSERT INTO BOOK (AUTHOR, TITLE, YEAROFPUBLICATION) VALUES ('Ernest Hemingway','Starec a more', 1965)

INSERT INTO BOOK (AUTHOR, TITLE, YEAROFPUBLICATION) VALUES ('Josef Skvorecky','Tankovy prapor', 1975)

INSERT INTO BOOK (AUTHOR, TITLE, YEAROFPUBLICATION) VALUES ('Umberto Ecco','Jmeno ruze', 1900)

INSERT INTO BOOK (AUTHOR, TITLE, YEAROFPUBLICATION) VALUES ('Ludwig','Konec prokrastinace', 2012)

INSERT INTO BOOK (AUTHOR, TITLE, YEAROFPUBLICATION) VALUES ('Bohumil Hrabal','Postriziny', 1965)
